0xPlaygrounds/rig

- rig-core/src/providers/cohere.rs
- rig-core/src/providers/openai.rs
Add logging of HTTP errors from provider clients
> misc: Add logging of http errors

- rig-qdrant/src/lib.rs
Review and edit Qdrant integration docs
> docs(qdrant): complete docs review

- rig-neo4j/README.md
- rig-neo4j/src/vector_index.rs
Last minute doc and const adjustments. Otherwise, neo4j looks good 👍
> fix(neo4j): last minute doc and const adjustments

- rig-neo4j/src/lib.rs
> chore: update lib.rs

- rig-core/src/providers/openai.rs
Related to https://github.com/0xPlaygrounds/rig/issues/165
> Add additional check for empty tool_calls

- rig-core/examples/agent_with_deepseek.rs
- rig-core/src/providers/deepseek.rs
- rig-core/src/providers/mod.rs
feat: Add support for DeepSeek
> feat: Add support for DeepSeek

- rig-core/src/agent.rs
- rig-core/src/providers/anthropic/client.rs
- rig-core/src/providers/gemini/completion.rs
- rig-neo4j/examples/vector_search_simple.rs
- **agent.rs**: Fixed spelling of "reprensenting" to "representing".
- **client.rs**: Corrected "proably" to "probably".
- **completion.rs**: Fixed spelling issues like "respponse" to "response" and "dificult" to "difficult".
- **vector_search_simple.rs**: Corrected "reprensent" to "represent".
> Fix typographical errors

- rig-mongodb/examples/vector_search_mongodb.rs
> fix: mongodb vector search example

- rig-core/examples/agent_autonomous.rs
- rig-core/examples/agent_evaluator_optimizer.rs
- rig-core/examples/agent_orchestrator.rs
- rig-core/examples/agent_parallelization.rs
- rig-core/examples/agent_prompt_chaining.rs
- rig-core/examples/agent_routing.rs
Adds recipe agent examples from [the agent recipes website](https://www.agentrecipes.com/) inspired by Anthropic, but in Rust.
Some of the examples are not directly from the recipes website.
> docs: agent recipes

- rig-core/src/providers/deepseek.rs
> Correct `tracing::debug` message.

- rig-core/examples/agent_with_deepseek.rs
- rig-core/src/providers/deepseek.rs
> fix: deepseek client auth

- rig-fastembed/Cargo.toml
> fix(rig-fastembed): crate info

- rig-core/src/streaming.rs
tiny change, `Send` is crucial, mb for dropping it in the previous PR 😄
> feat; add Send to StreamingResult inner Stream

- rig-core/examples/agent_with_grok.rs
- rig-core/examples/multi_turn_agent.rs
- rig-core/src/embeddings/embed.rs
- rig-core/src/providers/moonshot.rs
The trace message is wrong when refactoring the codes. Use this commit to correct them.
> fix: enhance tracing messages

- rig-core/examples/agent_with_echochambers.rs
This PR adds a comprehensive example demonstrating integration with the EchoChambers API, showcasing Rig's capabilities for building AI agents that can interact with external chat platforms.
- **Message Sending**: Send messages to EchoChambers rooms with proper formatting and sender information
- **Message History**: Retrieve and analyze message history from rooms
- **Room Metrics**: Get various metrics about rooms and agent performance
- **Dynamic Tool Selection**: Uses Rig's dynamic tool system for semantic tool selection
1. `SendMessage`
- Sends formatted messages to specified rooms
- Handles proper content wrapping and sender metadata
- Includes error handling for API responses
2. `GetHistory`
- Retrieves message history with configurable limits
- Supports pagination and filtering
- …
> EchoChambers Example Integration

- Cargo.lock
- rig-qdrant/Cargo.toml
- rig-qdrant/examples/qdrant_vector_search.rs
- rig-qdrant/src/lib.rs
Fixes #281 
Additionally adds a method for getting the inner client.
> feat: upsert documents into qdrant

- CONTRIBUTING.md
hey ! I found broken link //fix it
> fix link CONTRIBUTING.md

- rig-core/examples/agent_with_huggingface.rs
https://github.com/0xPlaygrounds/rig/pull/377
> fix spelling issues agent_with_huggingface.rs 

- Cargo.lock
- rig-core/Cargo.toml
- rig-core/examples/mcp_tool.rs
- rig-core/src/tool.rs
relates to [PR #438](https://github.com/0xPlaygrounds/rig/issues/438)
> fix: bump mcp-core to latest version and fixed breaking changes

- rig-core/src/completion/message.rs
Fixes #459
Correct ToolCall to Assistant message conversion
> fix(message): correct ToolCall to Message conversion

- Cargo.lock
- rig-lancedb/Cargo.toml
Update lancedb to the latest version 0.21
> Bump lancedb to version 0.21

- rig-core/src/providers/ollama.rs
Fixes #579 
Fixes RIG-811
cc @Benaiad - feel free to review this if you have time to do so!
> fix(rig-811): ollama fails to return results from multiple tools

- rig-core/src/providers/xai/completion.rs
Adds the GROK_4 model constant to the xAI completion provider.
- Added `GROK_4` constant with model identifier `"grok-4-0709"`
- Extends available xAI model options for completion requests
> feat: Add GROK_4 model constant to xAI provider

- rig-core/src/agent/mod.rs
> feat(rig-898): make MultiTurnStreamItem pub

- rig-core/src/providers/deepseek.rs
- rig-core/src/providers/groq.rs
- rig-core/src/providers/openai/completion/mod.rs
- rig-core/src/providers/openai/completion/streaming.rs
- rig-core/src/providers/openrouter/streaming.rs
> refactor(openAI, openrouter, deepseek, groq): use `reqwest-eventsource`

- rig-core/src/providers/ollama.rs
Here are the fixes I propose. I'm not entirely sure everything is correct, so please review the code.
[ #825](https://github.com/0xPlaygrounds/rig/issues/825)
> Fix:  parse NDJSON correctly, fixes #825

- rig-core/src/providers/huggingface/completion.rs
> bug(rig-959): Documents in Huggingface are not converted properly
