rig-core/src/providers/openai.rs

Quick PR for the new OpenAI models

feat(openai): add o1-preview and o1-mini

---

rig-core/examples/vector_search.rs
rig-core/src/vector_store/in_memory_store.rs

- Add `InMemoryVectorStore::from_documents` utility method
- Add `InMemoryVectorStore::from_embeddings` utility method
- Add docstrings
- Update example
Previously:
```rust
let model = openai_client.embedding_model("text-embedding-ada-002");
let mut vector_store = InMemoryVectorStore::default();
let embeddings = EmbeddingsBuilder::new(model.clone())
.simple_document("doc0", "Definition of a *flurbo*: A flurbo is a green alien that lives on cold planets")
.simple_document("doc1", "Definition of a *glarb-glarb*: A glarb-glarb is a ancient tool used by the ancestors of the inhabitants of planet Jiro to farm the land.")
.simple_document("doc2", "Definition of a *linglingdong*: A term used by inhabitants of the far side of the moon to describe humans.")
.build()
.await?; …
```

feat: Add utility methods to simplify InMemoryVectorStore creation

---

rig-core/src/completion.rs
rig-core/src/providers/anthropic/completion.rs
rig-core/src/providers/openai.rs
rig-core/src/providers/perplexity.rs

Context documents get prepended to the prompt user message rather than to system messages.

fix: move context documents to user prompt message

---

Cargo.lock
Cargo.toml
rig-core/examples/vector_search.rs
rig-mongodb/examples/vector_search_mongodb.rs
rig-qdrant/Cargo.toml
rig-qdrant/LICENSE
rig-qdrant/README.md
rig-qdrant/examples/qdrant_vector_search.rs
rig-qdrant/src/lib.rs

Adds support for Qdrant - https://qdrant.tech/ to be used as vector store in Rig.
Resolves #2 
I've QA tested and you can run the example with
```bash
export OPENAI_API_KEY=sk-********
```
```bash
docker run -p 6333:6333 -p 6334:6334 qdrant/qdrant
```
```bash
cargo run --release --example qdrant_vector_search
```
You can view the data at http://localhost:6333/dashboard

feat: Qdrant support

---

rig-core/src/vector_store/mod.rs
rig-mongodb/examples/vector_search_mongodb.rs
rig-mongodb/src/lib.rs

Eliminate the embeddings field from the top_n lookup results to streamline the response structure. Also adds a `DocumentResponse` type that doesn't include the embeddings field to be used with `top_n` responses.
Additionally, this PR un-hardcoded `embeddings.vec` and dynamically looks up the embedded field from the vector search index (which also confirms whether it exists or not properly during construction).
> We remove the embeddings.vec field via an aggregation pipeline step after we've performed our vector search. I also noticed that embeddings.vec is hardcoded within the mongodb implementation. I didn't want to abstract that in this PR so i've also used the same const for the filtering.
Update: We make a call to mongodb to check all search indexes. We only handle 1 index w/ 1 …

fix(mongodb): remove embeddings from `top_n` lookup

---

Cargo.lock
Cargo.toml
rig-sqlite/Cargo.toml
rig-sqlite/LICENSE
rig-sqlite/README.md
rig-sqlite/examples/vector_search_sqlite.rs
rig-sqlite/src/lib.rs

Sqlite using [sqlite-vec](https://github.com/asg017/sqlite-vec)
Fixes # (issue)
Resolves #124 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce your results.
- Run example with `cargo run --package rig-sqlite --example vector_search_sqlite`
- [x I have commented my code, particularly in hard-to-understand areas
I think this might have some conflicts with #120?
Perhaps it would be easiest to merge this first then adapt it in that PR or I can adapt it after that is merged. It seems like it might remove a bunch of the code.

feat: Add support for Sqlite vector store

---

rig-core/src/providers/openai.rs

Make OpenAI provider more compatible with third-party APIs

---

rig-mongodb/tests/integration_tests.rs

Previously, the mongo integration test was failing with `Error connecting to Search Index Management service.`. This is because it takes a bit of time for the container to initialize the service.
The extra delay added in #153 doesn't quite fix the issue because the index creation happens before the delay.
Our integration tests will now retry a couple of times before attempting to create the index.

fix: mongodb integration test

---

rig-core/src/embeddings/builder.rs
rig-core/src/loaders/file.rs
rig-core/src/pipeline/mod.rs

chore: fix types

---

rig-core/examples/agent_with_ollama.rs

The current ollama URL throws an 404 (not found) error message. This PR fixes the bug

Fix 404 POST response message from Ollama due to wrong endpoint url

---

.gitignore
Cargo.lock
rig-core/Cargo.toml
rig-core/src/providers/anthropic/completion.rs
rig-core/src/providers/cohere.rs
rig-core/src/providers/gemini/completion.rs
rig-core/src/providers/gemini/embedding.rs
rig-core/src/providers/openai.rs
rig-core/src/providers/perplexity.rs
rig-core/src/providers/xai/completion.rs
rig-core/src/providers/xai/embedding.rs

This enables rig to work on CF workers which opens up a whole new dimension of use case to integrate with web based UI such as leptos.
The simple change is put behind a feature flag.

feat: add send sync for CF worker

---

rig-core/src/providers/gemini/client.rs

If using a transit api, base_url should have an incoming method.

Make gemini_client_from_url function public

---

rig-core/src/agent.rs
rig-core/src/completion.rs
rig-core/src/providers/anthropic/completion.rs
rig-core/src/providers/cohere.rs
rig-core/src/providers/eternalai.rs
rig-core/src/providers/gemini/completion.rs
rig-core/src/providers/openai.rs
rig-core/src/providers/xai/completion.rs

anthropic currently sends back a vec on `Content` structs. Before the fix we were matching on the first element of that. The first element of a ToolUse is rarely ever the tool but more often text so we were never actually getting the tool use as a CompletionResponse
The PR first tries to find a tool use in the vec then some text

fix: anthropic tool use

---

CONTRIBUTING.md

I noticed a small in the docwhere the link to the Conventional Commits website was missing the `https://` protocol. This caused the link to be broken. I’ve added the missing `https://` to ensure the link works correctly.  
Here’s the corrected line:  
```markdown  
Commit messages should follow the [Conventional Commit](https://conventionalcommits.org/en/v1.0.0) format (prefixing with `feat`, `fix`, etc.) as this integrates into our auto-releases via a [release-plz](https://github.com/MarcoIeni/release-plz) Github action.  
```  
LFG!

feat: Fix broken link to Conventional Commits doc

---

rig-core/examples/agent_with_hyperbolic.rs
rig-core/src/providers/hyperbolic.rs
rig-core/src/providers/mod.rs

Adds the Hyperbolic inference API for text generation.
Keeping this PR small as #236 should ideally be implemented before we start adding audio and image generation.
Closes #235 if we are not supporting Marketplace API in this PR.

feat: hyperbolic inference API

---

rig-core/examples/agent_with_deepseek.rs
rig-core/examples/agent_with_grok.rs
rig-core/examples/agent_with_tools.rs
rig-core/examples/anthropic_streaming_with_tools.rs
rig-core/examples/calculator_chatbot.rs
rig-core/examples/rag_dynamic_tools.rs

- Updated `"substract"` → `"subtract"` in the following files:
- `agent_with_deepseek.rs`
- `agent_with_grok.rs`
- `agent_with_tools.rs`
- `anthropic_streaming_with_tools.rs`
- `calculator_chatbot.rs`
- `rag_dynamic_tools.rs`

Fix typos  "substract" → "subtract"

---

rig-core/examples/extractor_with_deepseek.rs
rig-core/src/providers/deepseek.rs

example result: 
```bash
$ cargo r --example=extractor_with_deepseek
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.00s
DeepSeek: {
"first_name": "John",
"last_name": "Doe",
"job": "software engineer"
}
```

feat: support extractor for deepseek

---

rig-core/examples/agent_with_context.rs

Noticed a grammar issue in the documentation: "a ancient tool" → "an ancient tool."
Since *ancient* starts with a vowel sound, "an" is the correct article.
Fixed it to improve clarity.

fix: fix grammar mistake

---

rig-core/examples/agent_with_galadriel.rs
rig-core/src/providers/galadriel.rs
rig-core/src/providers/mod.rs

Adds Galadriel API provider integration.
Note that this was originally implemented in #188 but then had to be reverted due to a missing test that *should've* been ran not being run which mistakenly led to a merge. This has been reverted to ensure CI reliability in other PRs while we figure out exactly why the test isn't running. Otherwise, it's exactly the same file contents.
cc @kristjanpeterson1 (just as an FYI in case this doesn't get merged in time for Rig 0.8)

feat: galadriel api integration (redux)

---

rig-core/src/completion/message.rs
rig-postgres/Makefile

- Fixes misspelled words (`Convertable` → `Convertible`) in `message.rs`.  
- Corrects `gitAmmend` → `gitAmend` in `Makefile` for proper command naming.

Fix spelling errors in `Makefile` and `message.rs`**

---

rig-core/src/providers/openai.rs

Adding constants for OpenAI's latest model offerings to the OpenAI provider in RIG.
Provider website: https://openai.com
API documentation: https://platform.openai.com/docs/models
Added constants:
- O3_MINI: OpenAI's most efficient high-context model
- O3_MINI_2025_01_31: Date-specific version of O3-mini
- O1: OpenAI's base model
- O1_2024_12_17: Date-specific version of O1
These additions make it easier for RIG users to access OpenAI's newer, more cost-efficient models directly through the framework.
This is a minimal change that only adds constants for new OpenAI models. The O3-MINI model in particular offers improved efficiency for high-context operations, making it a valuable addition to the available model options in RIG.
x.com/affaanmustafa

feat(openai): add OpenAI model constants

---

rig-core/src/providers/openai.rs

OpenAI was returning an error in completion requests because outgoing "tool_calls" vector was being serialized as "[]" (empty vec) if there were no tool calls. This should fix it :)
Error that was being received:
```
|  ProviderError: {
|    "error": {
|      "message": "Invalid 'messages[2].tool_calls': empty array. Expected an array with minimum length 1, but got an empty array instead.",
|      "type": "invalid_request_error",
|      "param": "messages[2].tool_calls",
|      "code": "empty_array"
|    }
|  }
```

fix(openai): skip serializing empty tool_calls vector

---

rig-core/src/providers/openai.rs

This PR adds support for the new OpenAI GPT-4.5 models released in February 2025. The models added are:
gpt-4.5-preview
gpt-4.5-preview-2025-02-27
These models are now available through OpenAI's API and offer improved performance over previous GPT models.
Website: https://openai.com/
API Documentation: https://platform.openai.com/docs/api-reference
Testing
Verified models are correctly added to constants
Tested API calls with the new model identifiers
Confirmed response handling works as expected with the new models
Updated documentation to reflect new model capabilities
Checklist:
My code follows the style guidelines of this project
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
My changes generate no new warnings …

New model provider: OpenAI GPT-4.5 Addition

---

Cargo.lock
rig-core/Cargo.toml

https://github.com/0xPlaygrounds/rig/issues/310
* enable feature of reqwest to support socks proxy

fix: reqwest can not use SOCKS proxy

---

rig-core/examples/agent_with_mira.rs
rig-core/src/providers/mira.rs
rig-core/src/providers/mod.rs

This pull request introduces support for Mira's API, providing a unified interface for accessing various LLM models. The integration enables Rig users to leverage Mira's API for AI-powered text completions efficiently.  
- **New `mira` provider module** with a complete API client implementation.  
- **API key authentication** for secure and straightforward access.  
- **Chat completion support** with customizable parameters.  
- **Model listing functionality** to retrieve available LLM models.  
- **Credit management capabilities**, including balance checks and transaction history.  
- **Comprehensive test coverage** to ensure reliability and stability.  
- Introduced a `Client` struct with methods for interacting with Mira's API endpoints.  
- Implemented robust error handling to manage …

feat: mira integration

---

rig-core/src/agent.rs
rig-core/src/providers/anthropic/decoders/jsonl.rs
rig-core/src/providers/anthropic/decoders/line.rs
rig-core/src/providers/anthropic/decoders/mod.rs
rig-core/src/providers/anthropic/decoders/sse.rs
rig-core/src/providers/anthropic/mod.rs
rig-core/src/providers/anthropic/streaming.rs
rig-core/src/streaming.rs

This fixes the issue with trailing whitespace JSONL and improves the flow of accumulating/streaming chunked outputs
The logic can likely be reused with minimal change for other providers

feat: SSE/JSONL decoders ported from Anthropic TS SDK

---

rig-core/src/providers/azure.rs

This pull requests extends the Azure OpenAI Client to provide authentication via token.
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#authentication

feat: Azure OpenAI Token Authentication

---

Cargo.lock
rig-core/Cargo.toml
rig-eternalai/Cargo.toml

Added `reqwest/rustls-tls` support to `rig-core`
After making this change, I can use [cross](https://github.com/cross-rs/cross) to compile Linux binaries on macOS without encountering the `No package 'openssl' found` error:
Cargo.toml:
```toml
rig-core = { version = "*", default-features = false, features = ["reqwest-rustls"] }
```
Build command:
```bash
cross build --release --target x86_64-unknown-linux-musl
```
https://discord.com/channels/896944341598208070/1280574327141695609/1333908613261164695

feat: add reqwest/rustls-tls support

---

rig-fastembed/Cargo.toml
rig-fastembed/examples/vector_search_local.rs
rig-fastembed/src/lib.rs

This example shows how to load files for fastembed from custom path.

example: load files for fastembed from custom path.

---

rig-core/src/streaming.rs
rig-neo4j/src/lib.rs
rig-neo4j/src/vector_index.rs
rig-qdrant/src/lib.rs

**Summary**
- Cleaned up some doc comments that Clippy flagged for over-indentation.
- Switched from `std::io::Error::new(ErrorKind::Other, ...)` to `Error::other(...)` in a couple of places to satisfy Clippy’s rules.
**Details**
- In `rig-qdrant` and `rig-neo4j`, I reduced extra whitespace in a few doc comments so they line up properly.
- In `rig-core`, changed `Error::new(...)` calls to `Error::other(...)` for a tidier approach.
Everything still builds fine under `cargo clippy --all -- -D warnings`, with no new warnings.

Fix Clippy warnings for doc indentation and Error::other usage

---

rig-core/src/providers/xai/completion.rs

Hi! I fixed broken xAI API reference link in `completion.rs` - updated old endpoint URL (`docs.x.ai/api/endpoints#chat-completions`) to current docs structure (`docs.x.ai/docs/api-reference#chat-completions`). Verified new link works and points to correct API documentation.

chore: fixed broken link xaiAPI in `completion.rs`

---

Cargo.lock
rig-bedrock/Cargo.toml
rig-bedrock/src/client.rs

The current ClientBuilder is limited. Instead of adding more options, we
now provide a way to externally configure and inject a client.

Support custom clients for bedrock

---

rig-core/src/providers/deepseek.rs
rig-core/src/providers/huggingface/completion.rs
rig-core/src/providers/hyperbolic.rs
rig-core/src/providers/openrouter.rs
rig-core/src/providers/xai/completion.rs
rig-eternalai/src/providers/eternalai.rs

Following on from #414 ,In fact, not only Deepseek, but other providers besides OpenAI and Anthropic also have the same issue.

fix: function call conversion typo

---

rig-core/src/providers/xai/embedding.rs

Found a broken link to xAI documentation in embedding.rs.
Since the reference URL no longer works, we removed the link to prevent confusion and keep the documentation clean.

Fix: Remove broken xAI reference link in embedding.rs

---

Cargo.lock
rig-core/Cargo.toml
rig-core/examples/mcp_tool.rs
rig-core/src/agent/prompt_request.rs
rig-core/src/tool.rs

- Remove use of async closure 
> ~Async closures are unstable in Rust 2021 edition, but are stabilized in Rust 2024 edition~, needs rust 1.85
- Bump mcp-core , mcp-core-macros and address compile errors 
> 1. fix missing match case
> 2. add annotations in tool macro use

Donot use async closure + Bump mcp-core

---

rig-neo4j/src/lib.rs

I found that the previous link pointed to a non-existing repository.
I updated it to the current working repository RIG_AI/RIG_AI, as there are no other available alternatives at the moment.
If you have a better or more specific repository in mind, please suggest it, and I will update the link accordingly.

fix: update broken link 

---

rig-core/src/extractor.rs

Fix a typo by changing "event with default values" to "even with default values" in the extractor prompt.

fix(extractor): correct typo in extractor prompt

---

rig-core/src/vector_store/in_memory_store.rs

Spotted and fixed a few wording hiccups:
`and and` - fix duplicate

polishing docs: error fixes for clarity

---

rig-core/src/providers/ollama.rs

This allows configuring the ollama url via the OLLAMA_API_BASE_URL environment variable.

feat(ollama): add support for OLLAMA_API_BASE_URL environment var

---

rig-mongodb/src/lib.rs
rig-mongodb/tests/integration_tests.rs

Implements the `InsertDocuments` trait for `MongoDbVectorIndex` as the part of #565.
- ✅ Add `InsertDocuments` trait implementation for MongoDB vector store
- ✅ Handle document transformation to BSON format  
- ✅ Support `OneOrMany<Embedding>` conversion
- ✅ Integration tests pass
- Transforms `Vec<(Doc, OneOrMany<Embedding>)>` to MongoDB BSON documents
- Uses `collection.clone_with_type::<mongodb::bson::Document>()` for proper type handling
- Flattens multiple embeddings per document into separate BSON documents
- ✅ Integration tests pass with mocked APIs
- ✅ Documents successfully inserted into MongoDB collections

feat(rig-mongodb): implement InsertDocuments trait

---

rig-core/src/agent/builder.rs
rig-core/src/agent/completion.rs
rig-core/src/agent/prompt_request.rs

Added also some instrumentation
```
2025-07-29T16:01:40.239264Z  INFO send{agent_name="Unnamed Agent"}: rig::agent::prompt_request: Current conversation depth: 1/20
2025-07-29T16:01:40.327220Z  INFO send{agent_name="Unnamed Agent"}:completion{agent_name="Unnamed Agent"}: rig: Selected documents: get_ticket_by_priority (0.3910402831735857)
2025-07-29T16:01:42.670064Z  INFO send{agent_name="Unnamed Agent"}: rig: Calling tool get_ticket_by_priority with args:
"{\"limit\":2,\"priority\":\"medium\"}"
2025-07-29T16:01:42.686429Z  INFO send{agent_name="Unnamed Agent"}: rig::agent::prompt_request: Current conversation depth: 2/20
2025-07-29T16:01:42.700915Z  INFO send{agent_name="Unnamed Agent"}:completion{agent_name="Unnamed Agent"}: rig: Selected documents: get_ticket_by_priority …
```

feat: Add agent name

---

rig-core/examples/agent.rs
rig-core/examples/agent_autonomous.rs
rig-core/examples/agent_evaluator_optimizer.rs
rig-core/examples/agent_orchestrator.rs
rig-core/examples/agent_parallelization.rs
rig-core/examples/agent_prompt_chaining.rs
rig-core/examples/agent_routing.rs
rig-core/examples/agent_with_echochambers.rs
rig-core/examples/agent_with_loaders.rs
rig-core/examples/calculator_chatbot.rs
rig-core/examples/chain.rs
rig-core/examples/debate.rs
rig-core/examples/multi_agent.rs
rig-core/examples/openai_agent_completions_api.rs
rig-core/examples/rag.rs
rig-core/examples/rag_dynamic_tools.rs
rig-core/examples/rag_dynamic_tools_multi_turn.rs
rig-core/examples/vector_search.rs
rig-core/src/providers/openai/client.rs

Allow constructing an OpenAI client with a custom base url from the environment variable OPENAI_BASE_URL, similar to the Python client.
This PR also migrates all the examples which were previously directly reading the environment to instead use the `openai::client::from_env` constructor.
Tested by building. I'm not able to run the examples E2E due to #658 , but the behavior appears to be correct for some that I spot-checked.

feat: Read the OPENAI_BASE_URL env variable when constructing an OpenAI client from_env

---

rig-core/src/providers/gemini/completion.rs

Some tools, like Context7, may return tool result as plain-text instead of json and thus serde_json::from_str will fail. In that case, we treat the value as the original string instead of throwing the conversion error.

Accept plain-text tool result

---

Cargo.lock
rig-core/Cargo.toml
rig-core/src/tool.rs

Breaking change in rmcp: 
> CallToolResult.content is now Option<Vec<Content>> instead of Vec<Content>
https://github.com/modelcontextprotocol/rust-sdk/commit/fbc7ab70cab26fd4f8897e5f88463cd442e7c59d

Chore: Update rmcp to version 0.5

---

rig-core/src/providers/openai/completion/mod.rs

Some OpenAI completion types are inconsistently private, I need them public so that I can convert them into [OpenAPI generated types](https://github.com/Coral-Protocol/coral-rs/blob/261228cff76e5083dbd6f6fe670bbae23c9cf1a0/src/api.rs#L248)

Consistent visibility modifiers in OpenAI

---

rig-core/examples/agent_with_agent_tool.rs
rig-core/src/agent/mod.rs
rig-core/src/agent/tool.rs

Closes https://github.com/0xPlaygrounds/rig/issues/696.
- Implements `Tool` for `Agent`, so that an `Agent` can be added as a Tool to be used by another Agent.
- Adds new example `agent_with_agent_tool` to demonstrate an Agent using another Agent as a Tool.

feat: implement Tool for Agent

---

rig-bedrock/src/client.rs
rig-core/src/client/mod.rs
rig-core/src/client/verify.rs
rig-core/src/prelude.rs
rig-core/src/providers/anthropic/client.rs
rig-core/src/providers/azure.rs
rig-core/src/providers/cohere/client.rs
rig-core/src/providers/deepseek.rs
rig-core/src/providers/galadriel.rs
rig-core/src/providers/gemini/client.rs
rig-core/src/providers/groq.rs
rig-core/src/providers/huggingface/client.rs
rig-core/src/providers/hyperbolic.rs
rig-core/src/providers/mira.rs
rig-core/src/providers/mistral/client.rs
rig-core/src/providers/moonshot.rs
rig-core/src/providers/ollama.rs
rig-core/src/providers/openai/client.rs
rig-core/src/providers/openrouter/client.rs
rig-core/src/providers/perplexity.rs
rig-core/src/providers/together/client.rs
rig-core/src/providers/voyageai.rs
rig-core/src/providers/xai/client.rs

Allow user to verify if a client is valid without consuming tokens.
The way I built this:
1. Try to use a key verification api if available
2. Fallback to models api
3. Otherwise always return Ok

Add verify client

---

rig-core/src/providers/openai/responses_api/mod.rs
rig-core/tests/openai_response_schema.rs

- Add add_props_false() helper function
- Process $defs, properties, items, and schema composition (anyOf/oneOf/allOf)
- Handle nested structs, arrays, and enums in OpenAI Responses API
- Add tests for these schema patterns
Fixes #743

fix(openai responses): recursively add additionalProperties: false 

---

rig-core/examples/agent_with_echochambers.rs
rig-core/examples/calculator_chatbot.rs
rig-core/examples/multi_agent.rs
rig-core/examples/pdf_agent.rs
rig-core/src/cli_chatbot.rs

Fixes #742 
- Replaced the `cli_chatbot` function with `Chatbot` and `ChatbotBuilder`
- Type-safe builder using the "type-state" pattern, where the `build` method is not available until the agent has been set
- Added configuration options for multi-turn depth and displaying token usage
- Added streaming requests, with response chunks printed as they are received
- Refactored examples using `cli_chatbot`
```rust
let chatbot = ChatbotBuilder::new()
.agent(my_agent)
.multi_turn_depth(1)
.show_usage()
.build();
chatbot.run().await?;
```
- I wasn't able to match the API @joshua-mo-143 suggested exactly (`Chatbot::builder`) due to inference issues with the generic parameter in `Agent<M>`. 
- The multi-agent example had to be refactored significantly to match the new API. It now composes agents …

feat(rig-904): Rework CLI chatbot integration

---

rig-core/src/tools/think.rs

chore: fix typo in comment

---

Cargo.lock
rig-bedrock/src/types/document.rs

this is a workaround for a bug inside aws bedrock sdk.
Bug is reported here: [aws-sdk-bedrockruntime DocumentSource bug #1365](https://github.com/awslabs/aws-sdk-rust/issues/1365)

bugfix: bedrock provider SDK has issue with DocumentBlock text variant

---

README.md

Add VT Code project to Who is using Rig in production? section in the README. VT Code uses `rig` for unifying and simplify LLM calls.

feat: add VT Code project to the README
